---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satizapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satizapp
  template:
    metadata:
      labels:
        app: satizapp
    spec:
      containers:
      - name: satizapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: newservice
spec:
  selector:
    app: satizapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001