apiVersion: apps/v1
kind: Deployment
metadata:
  name: satizapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: satizapp
  template:
    metadata:
      labels:
        app: satizapp
    spec:
      containers:
      - name: satizapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
