kind: Pod
apiVersion: v1
metadata:
  name: multicontainerpod
spec:
 volumes:
 - name: myvolume
   emptyDir: {}
 containers:
 - name: nginx-container
   image: nginx
   volumeMounts:
   - name: myvolume
     mountPath: /usr/share/nginx/html
 - name: debian-container
   image: debian
   volumeMounts:
   - name: myvolume
     mountPath: /html
