apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: debian-container
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
         echo "welcome to nginx" >> /html/index.html;
          sleep 10;
        done