apiVersion: v1
kind: Pod
metadata:
  name: satizapp
  labels:
    name: satizapp
spec:
  containers:
  - name: satizapp
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
